# Generated by Django 4.2.26 on 2026-02-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.DecimalField(decimal_places=2, max_digits=3, primary_key=True, serialize=False),
        ),
    ]
